include:
  - project: tools/shared-pipelines
    ref: v5.0.6
    file: /base/base.yaml
  - project: tools/shared-pipelines
    ref: v5.0.6
    file: /dart/dart.yaml

# Prepare
prepare-precache:
  extends: .prepare-dart-precache

# Analysis - general
analysis-spell-check:
  extends: .analysis-base-spell-check

analysis-security:
  extends: .analysis-base-security

analysis-licenses:
  extends: .analysis-dart-licenses

analysis-pana:
  extends: .analysis-dart-packages

analysis-build-runner:
  extends: .analysis-dart-build-runner

analysis-lint-maker:
  extends:
    - .setup-dart-fvm-melos
  stage: analysis
  script:
    - melos run lint_maker
    # Fail when changes are detected
    - git --no-pager diff --exit-code

# Analysis -style
analysis-lint:
  extends: .analysis-dart-lint

analysis-format:
  extends: .analysis-dart-format

# Test
test:
  extends: .test-dart
