include:
  - project: tools/shared-pipelines
    ref: v7.9.1
    file: /base/base.yaml
  - project: tools/shared-pipelines
    ref: v7.9.1
    file: /dart/dart.yaml

# Prepare
prepare-precache:
  extends: .prepare-dart-precache

# Audit
audit-security:
  extends: .audit-base-security

audit-licenses:
  extends: .audit-dart-licenses

# Analysis
analysis-pana:
  extends: .analysis-dart-packages

analysis-build-runner:
  extends: .analysis-dart-build-runner

analysis-lint-maker:
  extends:
    - .setup-dart-fvm-melos
  stage: analysis
  script:
    - melos run lint_maker
    # Fail when changes are detected
    - git --no-pager diff --exit-code -- **/analysis_options.yaml

# Analysis -style
analysis-lint:
  extends: .analysis-dart-lint

analysis-format:
  extends: .analysis-dart-format

# Test
test:
  extends: .test-dart
